language: java
install: gradle wrapper --gradle-version 4.2
jdk:
  - oraclejdk8
dist:
  trusty
before_script:
  - chmod +x gradlew
script:
  - ./gradlew :cqrs:check
  - ./gradlew :cqrs:check:codeCoverageReport
after_success:
  - bash <(curl -s https://codecov.io/bash)